-- Replaces the complete project catalog with the six approved portfolio projects.
begin;

delete from public.projects;

insert into public.projects
  (title, subtitle, description, challenge, outcome, tags, image, metric, period, case_study_url, linkedin_post_url, sort_order)
values
  ('AutoValue SL', 'Car price intelligence for Sri Lanka', 'Vehicle valuation platform powered by an ensemble model trained on 9,788 real Sri Lankan listings.', 'Turn inconsistent vehicle-listing data into a practical price estimate.', 'Gradient Boosting achieved a test R² of 0.875.', array['Python','Scikit-learn','Pandas','Flask'], '/autovalue-project.png', 'R² 0.875', 'Jan 2026', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=0', 'https://www.linkedin.com/posts/jananjaya2003_machinelearning-artificialintelligence-datascience-activity-7471475691746750464-Xj_Y', 0),
  ('PhishGuard AI', 'Real-time phishing URL detection', 'AI-powered URL scanner that returns a clear phishing verdict and risk probability.', 'Detect suspicious URLs quickly without relying on a single blacklist.', 'Extracts and evaluates nine URL signals to produce an interpretable risk result.', array['Python','Flask','AI','Cybersecurity'], '/phishguard-project.png', '9 URL signals', 'Jan 2026', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=2', 'https://www.linkedin.com/posts/jananjaya2003_machinelearning-cybersecurity-python-activity-7471783572601737217-7roc', 1),
  ('JBSUPER POS', 'Retail billing and receipt system', 'Point-of-sale application with catalog search, billing, loyalty points, receipt printing and PDF export.', 'Keep repeated cashier workflows fast, readable and reliable.', 'Combined product lookup, live totals and complete receipt handling in one interface.', array['Python','MySQL','POS','PDF Export'], '/jbsuper-pos.png', '100 products', 'Mar 2026', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=3', 'https://www.linkedin.com/posts/jananjaya2003_pos-webdevelopment-python-activity-7443548273849856001-6teU', 2),
  ('UK Vehicle Import Calculator', 'Import duty, VAT and excise estimation', 'Vehicle import utility with VIN lookup and structured duty, VAT and excise calculations.', 'Present a complicated import-cost process as a clear guided workflow.', 'Separated vehicle lookup, duty and tax calculations into practical calculator panels.', array['JavaScript','API','Tax Logic','Responsive UI'], '/vehicle-tax-calculator.png', 'VIN + tax', 'Feb 2026', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=4', null, 3),
  ('EV Price Prediction Sri Lanka', 'Six-month electric vehicle forecasting', 'Linear-regression application that forecasts monthly EV price movement for the Sri Lankan market.', 'Turn historical market signals into understandable month-by-month estimates.', 'Created a guided EV form and six-month forecast presented in LKR.', array['Python','Linear Regression','Forecasting','EV Data'], '/ev-price-prediction.png', '6-month forecast', '2026', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=1', 'https://www.linkedin.com/posts/jananjaya2003_electricvehicles-machinelearning-byd-activity-7471786823778861056-J8a9', 4),
  ('Yakafinity', 'Premium technology services platform', 'Business website presenting AI solutions, development, marketing, hosting and managed technology services.', 'Build a trustworthy service brand that communicates a broad technical offering clearly.', 'Combined business messaging, responsive interface design and scalable service navigation.', array['Next.js','Web Design','AI Services','Brand UI'], '/yakafinity-project.png', '5 core services', 'Dec 2025 — Present', 'https://yakafinity.com/my%20portfolio/project-detail.html?project=5', null, 5);

commit;
